@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@url = http://{{host}}

# @name get-prompts
GET {{url}}/prompts

###

# @name upload
POST {{url}}/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: image/png

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST {{url}}/videos/dbb83567-88cf-443a-92be-a50b713804db/transcription
Content-Type: application/json

{
  "prompt": "news, amazon, plane crash"
}

###

# @name create-transcription
POST {{url}}/ai/complete
Content-Type: application/json

{
  "videoId": "dbb83567-88cf-443a-92be-a50b713804db",
  "temperature": 0.5,
  "prompt": "Generate a simple resume from the following transcription: '''{transcription}'''"
}

